import type { AcceptanceStatus,ActivityRecord,ActivityUnit,IncidentRecord,IntakeLotDispositionDecision,NoveltyType,ReceptionRecord,Worker } from "@/lib/domain";
export type OpsAccessRole="operator"|"supervisor"|"technical"|"maintenance"|"admin"|"director"; export type OpsBackendStatus="booting"|"ready"|"error";
export type PlantAccess={dbId:string;plantId:string;code:string;name:string;role:OpsAccessRole};
export type RemoteOpsSnapshot={workers:Worker[];activities:ActivityRecord[];incidents:IncidentRecord[];receptions:ReceptionRecord[]};
export type OpsBackendState={mode:"local"|"supabase";status:OpsBackendStatus;error?:string};
export type RemoteEmployeeRow={id:string;plant_id:string;display_name:string;historical?:boolean|null};
export type RemoteIncidentRow={id:string;activity_id?:string|null;plant_id:string;severity:string;title:string;description?:string|null;opened_at:string;closed_at?:string|null;resolution_note?:string|null};
export type RemoteScheduledActivityRow={id:string;plant_id:string;title:string;process?:string|null;process_id?:string|null;activity_template_id?:string|null;equipment_id?:string|null;planned_start:string;planned_end?:string|null;status:"planned"|"running"|"done"|"delayed"|"missed"|"rescheduled";equipment_ref?:string|null;deviation_reason?:string|null};
export type RemoteActivityRow={id:string;plant_id:string;scheduled_activity_id?:string|null;title:string;process?:string|null;process_id?:string|null;activity_template_id?:string|null;equipment_id?:string|null;activity_comment?:string|null;started_at:string;ended_at?:string|null;quantity?:number|string|null;unit?:string|null;notes?:string|null;equipment_ref?:string|null;novelty_type?:NoveltyType|null;source_kind?:"app"|"historical"|null;import_run_id?:string|null;source_row_ids?:string[]|null};
export type RemoteActivityWorkerRow={activity_id:string;employee_id:string}; export type RemoteScheduledActivityWorkerRow={scheduled_activity_id:string;employee_id:string}; export type RemoteActivityToolRow={activity_id:string;tool_id:string}; export type RemoteOperationalToolRow={id:string;name:string};
export type RemoteActivityMappingExtras={scheduledWorkers?:RemoteScheduledActivityWorkerRow[];activityTools?:RemoteActivityToolRow[];tools?:RemoteOperationalToolRow[]};
export type RemoteReceiptRow={id:string;plant_id:string;generator:string;route:string;waste_type:ReceptionRecord["wasteType"];net_weight_kg:number|string;rejection_kg:number|string;rejection_known?:boolean|null;accepted_weight_kg?:number|string|null;improper_weight_kg?:number|string|null;acceptance_status:AcceptanceStatus;observation?:string|null;started_at:string;ended_at:string;lot_code:string;source_kind?:"app"|"historical"|null;time_precision?:"datetime"|"date_only"|null;import_run_id?:string|null;source_row_ids?:string[]|null};
export type RemoteIntakeLotRow={id:string;plant_id:string;receipt_id:string;lot_code:string;initial_mass_kg:number|string;available_mass_kg:number|string;status:"available"|"quarantined"|"in_process"|"depleted"|"rejected"};
export type RemoteIntakeLotDispositionRow={lot_id:string;plant_id:string;decision:IntakeLotDispositionDecision;reason:string;decided_at:string};
function normalizeText(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase();}
export function canonicalPlantId(code:string,name=""){const c=normalizeText(`${code} ${name}`);if(c.includes("yarumal")||c.includes("yar"))return"yarumal";if(c.includes("tamesis")||c.includes("tam"))return"tamesis";return normalizeText(code).replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
export function plantAccessByDbId(access:PlantAccess[]){return new Map(access.map(p=>[p.dbId,p]));}
export function mapRemoteEmployee(row:RemoteEmployeeRow,access:PlantAccess[]):Worker{const p=plantAccessByDbId(access).get(row.plant_id);if(!p)throw new Error(`Sin membresía visible para la planta remota ${row.plant_id}.`);return{id:row.id,name:row.display_name,plantId:p.plantId,historical:Boolean(row.historical)||undefined};}
const incidentSeverities=new Set<IncidentRecord["severity"]>(["high","medium","low"]);
export function mapRemoteIncident(row:RemoteIncidentRow,access:PlantAccess[]):IncidentRecord{const plant=plantAccessByDbId(access).get(row.plant_id);if(!plant)throw new Error(`Sin membresía visible para la planta remota ${row.plant_id}.`);if(!incidentSeverities.has(row.severity as IncidentRecord["severity"]))throw new Error(`Incidente remoto ${row.id} tiene severidad inválida.`);return{id:row.id,activityId:row.activity_id||undefined,plantId:plant.plantId,plant:plant.name,title:row.title,detail:row.description?.trim()||"Sin detalle registrado.",severity:row.severity as IncidentRecord["severity"],openedAt:row.opened_at,closedAt:row.closed_at||undefined,resolutionNote:row.resolution_note?.trim()||undefined,status:row.closed_at?"closed":"open"};}
const activityUnits=new Set<ActivityUnit>(["kg","t","L","unidades","m3"]); function mapActivityUnit(u?:string|null){if(!u)return undefined;if(!activityUnits.has(u as ActivityUnit))throw new Error(`Unidad remota de actividad no soportada: ${u}.`);return u as ActivityUnit;} function numberOrUndefined(v?:number|string|null){if(v===null||v===undefined||v==="")return undefined;const n=Number(v);if(!Number.isFinite(n))throw new Error(`Valor numérico remoto inválido: ${v}.`);return n;}
function scheduledStatus(r:RemoteScheduledActivityRow):ActivityRecord["status"]{if(r.status==="planned"||r.status==="delayed"||r.status==="missed")return r.status;throw new Error(`Actividad programada ${r.id} está ${r.status} pero no tiene ejecución enlazada.`);}
function addUnique(map:Map<string,string[]>,key:string,value:string){const current=map.get(key)??[];if(!current.includes(value))current.push(value);map.set(key,current);}
function planningDeviationReason(row?:RemoteScheduledActivityRow){const value=row?.deviation_reason?.trim();return value||undefined;}
export function mapRemoteActivities(scheduledRows:RemoteScheduledActivityRow[],activityRows:RemoteActivityRow[],workerRows:RemoteActivityWorkerRow[],access:PlantAccess[],extras:RemoteActivityMappingExtras={}):ActivityRecord[]{
 const plants=plantAccessByDbId(access),scheduledById=new Map(scheduledRows.map(r=>[r.id,r])),actualScheduledIds=new Set(activityRows.flatMap(r=>r.scheduled_activity_id?[r.scheduled_activity_id]:[])),workerIdsByActivity=new Map<string,string[]>(),workerIdsBySchedule=new Map<string,string[]>(),toolIdsByActivity=new Map<string,string[]>(),toolNames=new Map((extras.tools??[]).map(t=>[t.id,t.name]));
 workerRows.forEach(w=>addUnique(workerIdsByActivity,w.activity_id,w.employee_id));(extras.scheduledWorkers??[]).forEach(w=>addUnique(workerIdsBySchedule,w.scheduled_activity_id,w.employee_id));(extras.activityTools??[]).forEach(t=>addUnique(toolIdsByActivity,t.activity_id,t.tool_id));
 const actual=activityRows.map((row):ActivityRecord=>{const plant=plants.get(row.plant_id);if(!plant)throw new Error(`Sin membresía visible para la planta remota ${row.plant_id}.`);const scheduled=row.scheduled_activity_id?scheduledById.get(row.scheduled_activity_id):undefined;if(row.scheduled_activity_id&&!scheduled)throw new Error(`La ejecución ${row.id} referencia una programación no visible.`);if(scheduled&&scheduled.plant_id!==row.plant_id)throw new Error(`La ejecución ${row.id} no coincide con la planta de su programación.`);const quantity=numberOrUndefined(row.quantity);if(quantity!==undefined&&quantity<=0)throw new Error(`La ejecución ${row.id} tiene cantidad inválida.`);const toolIds=toolIdsByActivity.get(row.id)??[];return{id:row.id,plantId:plant.plantId,plant:plant.name,title:row.title,process:row.process?.trim()||scheduled?.process?.trim()||"Sin proceso",processId:row.process_id||scheduled?.process_id||undefined,activityTemplateId:row.activity_template_id||scheduled?.activity_template_id||undefined,plannedStart:scheduled?.planned_start??row.started_at,plannedEnd:scheduled?.planned_end||undefined,actualStart:row.started_at,actualEnd:row.ended_at||undefined,workerIds:workerIdsByActivity.get(row.id)??[],equipment:row.equipment_ref?.trim()||scheduled?.equipment_ref?.trim()||undefined,equipmentId:row.equipment_id||scheduled?.equipment_id||undefined,toolIds,tools:toolIds.map(id=>toolNames.get(id)).filter((name):name is string=>Boolean(name)),comment:row.activity_comment?.trim()||undefined,status:row.ended_at?"done":"running",deviationReason:planningDeviationReason(scheduled),quantity,unit:quantity===undefined?undefined:mapActivityUnit(row.unit),noveltyType:row.novelty_type||undefined,novelty:row.novelty_type?row.notes?.trim()||undefined:undefined,source:row.source_kind==="historical"?"historical":scheduled?"scheduled":"unplanned",provenance:row.source_kind==="historical"&&row.import_run_id?{importRunId:row.import_run_id,sourceName:"Supabase histórico",sourceRowIds:row.source_row_ids??[]}:undefined};});
 const pending=scheduledRows.filter(r=>r.status!=="rescheduled"&&!actualScheduledIds.has(r.id)).map((row):ActivityRecord=>{const plant=plants.get(row.plant_id);if(!plant)throw new Error(`Sin membresía visible para la planta remota ${row.plant_id}.`);return{id:row.id,plantId:plant.plantId,plant:plant.name,title:row.title,process:row.process?.trim()||"Sin proceso",processId:row.process_id||undefined,activityTemplateId:row.activity_template_id||undefined,plannedStart:row.planned_start,plannedEnd:row.planned_end||undefined,workerIds:workerIdsBySchedule.get(row.id)??[],equipment:row.equipment_ref?.trim()||undefined,equipmentId:row.equipment_id||undefined,status:scheduledStatus(row),deviationReason:planningDeviationReason(row),source:"scheduled"};});return[...actual,...pending].sort((a,b)=>new Date(b.plannedStart).getTime()-new Date(a.plannedStart).getTime());
}
export function mapRemoteReceipt(row:RemoteReceiptRow,access:PlantAccess[],lot?:RemoteIntakeLotRow,disposition?:RemoteIntakeLotDispositionRow):ReceptionRecord{const plant=plantAccessByDbId(access).get(row.plant_id);if(!plant)throw new Error(`Sin membresía visible para la planta remota ${row.plant_id}.`);const netWeightKg=Number(row.net_weight_kg),rejectionKg=Number(row.rejection_kg),acceptedWeightKg=numberOrUndefined(row.accepted_weight_kg),improperWeightKg=numberOrUndefined(row.improper_weight_kg);if(!Number.isFinite(netWeightKg)||netWeightKg<=0)throw new Error(`Recepción remota ${row.id} tiene peso neto inválido.`);if(!Number.isFinite(rejectionKg)||rejectionKg<0||rejectionKg>netWeightKg)throw new Error(`Recepción remota ${row.id} tiene rechazo inválido.`);if(acceptedWeightKg!==undefined&&(acceptedWeightKg<0||acceptedWeightKg>netWeightKg))throw new Error(`Recepción remota ${row.id} tiene masa aceptada inválida.`);if(improperWeightKg!==undefined&&(improperWeightKg<0||improperWeightKg>rejectionKg))throw new Error(`Recepción remota ${row.id} tiene impropios inválidos.`);let physicalLot:ReceptionRecord["physicalLot"];if(lot){if(lot.receipt_id!==row.id||lot.plant_id!==row.plant_id||lot.lot_code!==row.lot_code)throw new Error(`El lote físico ${lot.id} no coincide con la recepción ${row.id}.`);const initialMassKg=Number(lot.initial_mass_kg),availableMassKg=Number(lot.available_mass_kg);if(!Number.isFinite(initialMassKg)||initialMassKg<=0||!Number.isFinite(availableMassKg)||availableMassKg<0||availableMassKg>initialMassKg)throw new Error(`El lote físico ${lot.id} tiene balance de masa inválido.`);if(disposition&&(disposition.lot_id!==lot.id||disposition.plant_id!==lot.plant_id))throw new Error(`La disposición técnica no coincide con el lote físico ${lot.id}.`);physicalLot={id:lot.id,initialMassKg,availableMassKg,status:lot.status,disposition:disposition?{decision:disposition.decision,reason:disposition.reason,decidedAt:disposition.decided_at}:undefined};}else if(disposition){throw new Error(`Existe una disposición técnica sin lote físico visible para la recepción ${row.id}.`);}return{id:row.id,plantId:plant.plantId,plant:plant.name,generator:row.generator,route:row.route,wasteType:row.waste_type,netWeightKg,rejectionKg,rejectionKnown:row.rejection_known??true,acceptedWeightKg,improperWeightKg,acceptance:row.acceptance_status,observation:row.observation||undefined,startedAt:row.started_at,endedAt:row.ended_at,lotCode:row.lot_code,physicalLot,source:row.source_kind==="historical"?"historical":"local",timePrecision:row.time_precision??"datetime",provenance:row.source_kind==="historical"&&row.import_run_id?{importRunId:row.import_run_id,sourceName:"Supabase histórico",sourceRowIds:row.source_row_ids??[]}:undefined};}
