"""V0.46: allow production password hashes generated by PBKDF2."""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "20260916_0030"
down_revision: Union[str, None] = "20260803_0029"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite installations receive the wider column through metadata creation;
    # PostgreSQL needs an explicit type change for an existing app_users table.
    if op.get_bind().dialect.name == "postgresql":
        op.alter_column(
            "app_users",
            "password_hash",
            existing_type=sa.String(length=64),
            type_=sa.String(length=255),
            existing_nullable=False,
        )


def downgrade() -> None:
    # Hashes longer than 64 characters cannot be safely truncated.
    pass
