import type { SupabaseClient } from "@supabase/supabase-js";
import type { ActivityUnit,NoveltyType } from "@/lib/domain"; import type { OpsIdentity } from "@/lib/ops-session"; import { createClient } from "@/lib/supabase/client";
import { canonicalPlantId,mapRemoteActivities,mapRemoteEmployee,mapRemoteReceipt,type OpsAccessRole,type PlantAccess,type RemoteActivityRow,type RemoteActivityToolRow,type RemoteActivityWorkerRow,type RemoteEmployeeRow,type RemoteOperationalToolRow,type RemoteOpsSnapshot,type RemoteReceiptRow,type RemoteScheduledActivityRow,type RemoteScheduledActivityWorkerRow } from "@/lib/ops-data-contract";
type MembershipRow={plant_id:string;role:OpsAccessRole;active:boolean;plants:{id:string;code:string;name:string;active:boolean}|{id:string;code:string;name:string;active:boolean}[]|null}; type ProfileRow={display_name:string;active:boolean};
export type StructuredRemoteCreateActivityPayload={plantId:string;templateId:string;workerIds:string[];startedAt:string;endedAt?:string;equipmentId?:string;toolIds?:string[];comment?:string;quantity?:number;unit?:ActivityUnit};
export type LegacyRemoteCreateActivityPayload={plantId:string;title:string;process:string;workerIds:string[];equipment?:string};
export type RemoteCreateActivityPayload=StructuredRemoteCreateActivityPayload|LegacyRemoteCreateActivityPayload;
export type RemoteFinishActivityPayload={quantity?:number;unit?:ActivityUnit;noveltyType?:NoveltyType;novelty?:string;openIncident?:boolean;comment?:string;toolIds?:string[]};
export type RemoteReceptionPayload={plantId:string;generator:string;route:string;wasteType:RemoteReceiptRow["waste_type"];netWeightKg:number;rejectionKg:number;acceptance:Exclude<RemoteReceiptRow["acceptance_status"],"unknown">;observation?:string;startedAt:string};
function errorMessage(scope:string,error:{message?:string}|null){return`${scope}: ${error?.message||"error remoto desconocido"}`;} function onePlant(v:MembershipRow["plants"]){return Array.isArray(v)?v[0]:v;} function remotePlantId(access:PlantAccess[],plantId:string){const p=access.find(i=>i.plantId===plantId);if(!p)throw new Error(`No tienes acceso a la planta ${plantId}.`);return p.dbId;}
export async function loadRemoteIdentity(client:SupabaseClient=createClient()):Promise<OpsIdentity>{const{data:authData,error:authError}=await client.auth.getUser();if(authError)throw new Error(errorMessage("No fue posible validar la sesión",authError));if(!authData.user)throw new Error("No hay una sesión autenticada para GREENATICS OPS.");const{data,error}=await client.from("profiles").select("display_name,active").eq("id",authData.user.id).maybeSingle();if(error)throw new Error(errorMessage("No fue posible cargar el perfil",error));const profile=data as ProfileRow|null;if(!profile)throw new Error("La cuenta autenticada todavía no tiene un perfil operativo creado.");if(!profile.active)throw new Error("El perfil de esta cuenta está inactivo.");return{userId:authData.user.id,displayName:profile.display_name,email:authData.user.email||undefined};}
export async function loadPlantAccess(client:SupabaseClient=createClient()):Promise<PlantAccess[]>{const{data:authData,error:authError}=await client.auth.getUser();if(authError)throw new Error(errorMessage("No fue posible validar la sesión",authError));if(!authData.user)throw new Error("No hay una sesión autenticada para GREENATICS OPS.");const{data,error}=await client.from("plant_memberships").select("plant_id,role,active,plants!inner(id,code,name,active)").eq("user_id",authData.user.id).eq("active",true);if(error)throw new Error(errorMessage("No fue posible cargar las plantas autorizadas",error));return((data??[])as unknown as MembershipRow[]).map(m=>{const p=onePlant(m.plants);if(!p||!p.active)return null;return{dbId:p.id,plantId:canonicalPlantId(p.code,p.name),code:p.code,name:p.name,role:m.role} satisfies PlantAccess;}).filter((p):p is PlantAccess=>Boolean(p));}
export async function loadRemoteOpsSnapshot(access:PlantAccess[],client:SupabaseClient=createClient()):Promise<RemoteOpsSnapshot>{if(!access.length)return{workers:[],activities:[],receptions:[]};const ids=access.map(p=>p.dbId);const [employees,scheduled,activities,workers,scheduledWorkers,activityTools,tools,receipts]=await Promise.all([
 client.from("employees").select("id,plant_id,display_name,historical").in("plant_id",ids).eq("active",true).order("display_name"),client.from("scheduled_activities").select("id,plant_id,title,process,process_id,activity_template_id,equipment_id,planned_start,planned_end,status,equipment_ref,deviation_reason").in("plant_id",ids).order("planned_start",{ascending:false}),client.from("activities").select("id,plant_id,scheduled_activity_id,title,process,process_id,activity_template_id,equipment_id,activity_comment,started_at,ended_at,quantity,unit,notes,equipment_ref,novelty_type,source_kind,import_run_id,source_row_ids").in("plant_id",ids).order("started_at",{ascending:false}),client.from("activity_workers").select("activity_id,employee_id"),client.from("scheduled_activity_workers").select("scheduled_activity_id,employee_id,plant_id").in("plant_id",ids),client.from("activity_tools").select("activity_id,tool_id,plant_id").in("plant_id",ids),client.from("operational_tools").select("id,name,plant_id").in("plant_id",ids),client.from("material_receipts").select("id,plant_id,generator,route,waste_type,net_weight_kg,rejection_kg,rejection_known,acceptance_status,observation,started_at,ended_at,lot_code,source_kind,time_precision,import_run_id,source_row_ids").in("plant_id",ids).order("ended_at",{ascending:false})]);
 const failed=[employees,scheduled,activities,workers,scheduledWorkers,activityTools,tools,receipts].find(r=>r.error);if(failed?.error)throw new Error(errorMessage("No fue posible cargar la operación",failed.error));return{workers:((employees.data??[])as unknown as RemoteEmployeeRow[]).map(r=>mapRemoteEmployee(r,access)),activities:mapRemoteActivities((scheduled.data??[])as unknown as RemoteScheduledActivityRow[],(activities.data??[])as unknown as RemoteActivityRow[],(workers.data??[])as unknown as RemoteActivityWorkerRow[],access,{scheduledWorkers:(scheduledWorkers.data??[])as unknown as RemoteScheduledActivityWorkerRow[],activityTools:(activityTools.data??[])as unknown as RemoteActivityToolRow[],tools:(tools.data??[])as unknown as RemoteOperationalToolRow[]}),receptions:((receipts.data??[])as unknown as RemoteReceiptRow[]).map(r=>mapRemoteReceipt(r,access))};}
export async function startRemoteScheduledActivity(id:string,workerIds:string[],client:SupabaseClient=createClient()){const{data,error}=await client.rpc("ops_start_scheduled_activity",{scheduled_id:id,employee_ids:workerIds});if(error)throw new Error(errorMessage("No fue posible iniciar la actividad",error));if(typeof data!=="string")throw new Error("La actividad fue iniciada pero el servidor no devolvió un identificador válido.");return data;}
export async function createRemoteUnplannedActivity(access:PlantAccess[],p:RemoteCreateActivityPayload,client:SupabaseClient=createClient()){if("templateId" in p){const{data,error}=await client.rpc("ops_record_activity_log",{target_plant:remotePlantId(access,p.plantId),target_template:p.templateId,employee_ids:p.workerIds,activity_started_at:p.startedAt,activity_ended_at:p.endedAt??null,target_equipment:p.equipmentId??null,tool_ids:p.toolIds??[],activity_comment:p.comment||null,result_quantity:p.quantity??null,result_unit:p.unit??null});if(error)throw new Error(errorMessage("No fue posible registrar la actividad",error));if(typeof data!=="string")throw new Error("La actividad fue creada pero el servidor no devolvió un identificador válido.");return data;}const{data,error}=await client.rpc("ops_create_unplanned_activity",{target_plant:remotePlantId(access,p.plantId),activity_title:p.title,activity_process:p.process,employee_ids:p.workerIds,equipment_ref:p.equipment||null});if(error)throw new Error(errorMessage("No fue posible registrar la actividad legacy",error));if(typeof data!=="string")throw new Error("La actividad fue creada pero el servidor no devolvió un identificador válido.");return data;}
export async function finishRemoteActivity(id:string,p:RemoteFinishActivityPayload,client:SupabaseClient=createClient()){const{data,error}=await client.rpc("ops_finish_activity_v2",{target_activity:id,result_quantity:p.quantity??null,result_unit:p.unit??null,novelty_kind:p.noveltyType??null,novelty_notes:p.novelty||null,open_incident:p.openIncident??false,activity_comment:p.comment||null,tool_ids:p.toolIds??[]});if(error)throw new Error(errorMessage("No fue posible finalizar la actividad",error));if(typeof data!=="string")throw new Error("La actividad fue finalizada pero el servidor no devolvió la hora de cierre.");return data;}
export async function createRemoteReception(access:PlantAccess[],p:RemoteReceptionPayload,client:SupabaseClient=createClient()){const endedAt=new Date().toISOString();const{data,error}=await client.rpc("ops_record_material_receipt",{target_plant:remotePlantId(access,p.plantId),generator_name:p.generator,route_name:p.route,waste_kind:p.wasteType,net_weight:p.netWeightKg,rejection_weight:p.rejectionKg,acceptance_kind:p.acceptance,receipt_started_at:p.startedAt,receipt_ended_at:endedAt,observation_text:p.observation||null});if(error)throw new Error(errorMessage("No fue posible registrar la recepción",error));const row=Array.isArray(data)?data[0]:data;if(!row||typeof row.id!=="string"||typeof row.lot_code!=="string")throw new Error("La recepción fue registrada pero el servidor no devolvió lote e identificador válidos.");return{id:row.id as string,lotCode:row.lot_code as string};}
export async function signOutRemote(client:SupabaseClient=createClient()){const{error}=await client.auth.signOut();if(error)throw new Error(errorMessage("No fue posible cerrar la sesión",error));}
