import type { SupabaseClient } from "@supabase/supabase-js";
import type { PlantAccess } from "@/lib/ops-data-contract";
import type { SettlementMethod,SettlementRecord } from "@/lib/settlement-domain";
import { createClient } from "@/lib/supabase/client";

type SettlementRow={id:string;plant_id:string;kind:SettlementRecord["kind"];sale_id?:string|null;expense_id?:string|null;amount_cop:number|string;occurred_on:string;method:SettlementMethod;reference?:string|null;note?:string|null;recorded_at:string};
type SaleRow={id:string;customer_id:string};type CustomerRow={id:string;name:string};type ExpenseRow={id:string;supplier_id:string};type SupplierRow={id:string;name:string};
export type RemoteSettlementInput={sourceId:string;amountCop:number;occurredOn:string;method:SettlementMethod;reference?:string;note?:string};
function errorMessage(scope:string,error:{message?:string}|null){return `${scope}: ${error?.message||"error remoto desconocido"}`;}
function positiveNumber(value:number|string,scope:string){const parsed=Number(value);if(!Number.isFinite(parsed)||parsed<=0)throw new Error(`${scope} contiene un monto inválido.`);return parsed;}

export async function loadRemoteSettlements(access:PlantAccess[],client:SupabaseClient=createClient()):Promise<SettlementRecord[]>{
  if(!access.length)return [];
  const plantIds=access.map((plant)=>plant.dbId);
  const settlementResult=await client.from("financial_settlements").select("id,plant_id,kind,sale_id,expense_id,amount_cop,occurred_on,method,reference,note,recorded_at").in("plant_id",plantIds).order("occurred_on",{ascending:false}).order("recorded_at",{ascending:false});
  if(settlementResult.error)throw new Error(errorMessage("No fue posible cargar recaudos/pagos",settlementResult.error));
  const rows=(settlementResult.data??[]) as unknown as SettlementRow[];const saleIds=rows.flatMap((row)=>row.sale_id?[row.sale_id]:[]);const expenseIds=rows.flatMap((row)=>row.expense_id?[row.expense_id]:[]);
  let sales:SaleRow[]=[];let customers:CustomerRow[]=[];let expenses:ExpenseRow[]=[];let suppliers:SupplierRow[]=[];
  if(saleIds.length){const saleResult=await client.from("sales").select("id,customer_id").in("id",saleIds);if(saleResult.error)throw new Error(errorMessage("No fue posible enlazar recaudos con ventas",saleResult.error));sales=(saleResult.data??[]) as unknown as SaleRow[];const customerIds=[...new Set(sales.map((row)=>row.customer_id))];if(customerIds.length){const customerResult=await client.from("customers").select("id,name").in("id",customerIds);if(customerResult.error)throw new Error(errorMessage("No fue posible enlazar clientes",customerResult.error));customers=(customerResult.data??[]) as unknown as CustomerRow[];}}
  if(expenseIds.length){const expenseResult=await client.from("operational_expenses").select("id,supplier_id").in("id",expenseIds);if(expenseResult.error)throw new Error(errorMessage("No fue posible enlazar pagos con compras/gastos",expenseResult.error));expenses=(expenseResult.data??[]) as unknown as ExpenseRow[];const supplierIds=[...new Set(expenses.map((row)=>row.supplier_id))];if(supplierIds.length){const supplierResult=await client.from("suppliers").select("id,name").in("id",supplierIds);if(supplierResult.error)throw new Error(errorMessage("No fue posible enlazar proveedores",supplierResult.error));suppliers=(supplierResult.data??[]) as unknown as SupplierRow[];}}
  const plantMap=new Map(access.map((plant)=>[plant.dbId,plant]));const customerMap=new Map(customers.map((row)=>[row.id,row.name]));const customerBySale=new Map(sales.map((row)=>[row.id,customerMap.get(row.customer_id)]));const supplierMap=new Map(suppliers.map((row)=>[row.id,row.name]));const supplierByExpense=new Map(expenses.map((row)=>[row.id,supplierMap.get(row.supplier_id)]));
  return rows.map((row):SettlementRecord=>{const plant=plantMap.get(row.plant_id);if(!plant)throw new Error(`Movimiento ${row.id} pertenece a una planta no visible.`);const sourceId=row.kind==="collection"?row.sale_id:row.expense_id;if(!sourceId)throw new Error(`Movimiento ${row.id} no tiene fuente válida.`);const counterparty=row.kind==="collection"?customerBySale.get(sourceId):supplierByExpense.get(sourceId);if(!counterparty)throw new Error(`Movimiento ${row.id} no pudo resolver su contraparte.`);return {id:row.id,kind:row.kind,sourceType:row.kind==="collection"?"sale":"expense",sourceId,plantId:plant.plantId,plant:plant.name,counterparty,amountCop:positiveNumber(row.amount_cop,`Movimiento ${row.id}`),occurredOn:row.occurred_on,method:row.method,reference:row.reference||undefined,note:row.note||undefined,recordedAt:row.recorded_at};});
}

export async function recordRemoteCollection(input:RemoteSettlementInput,client:SupabaseClient=createClient()){const {data,error}=await client.rpc("record_sale_collection",{p_sale_id:input.sourceId,p_amount_cop:input.amountCop,p_occurred_on:input.occurredOn,p_method:input.method,p_reference:input.reference||null,p_note:input.note||null});if(error)throw new Error(errorMessage("No fue posible registrar el recaudo",error));if(typeof data!=="string")throw new Error("El recaudo se registró pero el servidor no devolvió su identificador.");return data as string;}
export async function recordRemotePayment(input:RemoteSettlementInput,client:SupabaseClient=createClient()){const {data,error}=await client.rpc("record_expense_payment",{p_expense_id:input.sourceId,p_amount_cop:input.amountCop,p_occurred_on:input.occurredOn,p_method:input.method,p_reference:input.reference||null,p_note:input.note||null});if(error)throw new Error(errorMessage("No fue posible registrar el pago",error));if(typeof data!=="string")throw new Error("El pago se registró pero el servidor no devolvió su identificador.");return data as string;}
