#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
if [ -f .env ]; then
  set -a
  source .env
  set +a
fi
PY="${CTH_PYTHON_BIN:-/usr/local/bin/python}"
if [ ! -x "$PY" ]; then
  PY="$(command -v python)"
fi
export PYTHONPATH="$ROOT${PYTHONPATH:+:$PYTHONPATH}"
export APP_ENV="${APP_ENV:-production}"
export HOST="${HOST:-0.0.0.0}"
export PORT="${PORT:-10000}"
export OPEN_BROWSER=0
# Complete schema setup before serving traffic. This prevents a healthy
# container from exposing a half-initialized application to real users.
echo "Inicialización de base de datos iniciada." >&2
"$PY" -m alembic upgrade head
"$PY" - <<'PYCODE'
from sqlalchemy import select, text

from app.db.base import ENGINE, SessionLocal
from app.db.models import AppUser, Organization
from app.config import settings
from app.database import hash_password, init_db

# Keep startup safe for staging databases that were created by an earlier
# revision before the password hash migration existed.
if ENGINE.dialect.name == "postgresql":
    with ENGINE.begin() as connection:
        connection.execute(text("ALTER TABLE app_users ALTER COLUMN password_hash TYPE VARCHAR(255)"))
        # Repair staging databases whose Alembic history predates the security
        # table. Run this on the application engine so its search_path matches
        # the connections used by the login flow.
        schema_name = settings.database_schema or "public"
        if schema_name != "public":
            connection.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema_name}"'))
            connection.execute(text(f'SET search_path TO "{schema_name}", public'))
        core_organizations = f'"{schema_name}"."organizations"'
        core_users = f'"{schema_name}"."app_users"'
        connection.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {core_organizations} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(180) NOT NULL UNIQUE,
                trade_name VARCHAR(180) NOT NULL DEFAULT '',
                tax_id VARCHAR(30) NOT NULL,
                sector VARCHAR(100) NOT NULL,
                ciiu_code VARCHAR(20) NOT NULL DEFAULT '',
                country VARCHAR(80) NOT NULL DEFAULT 'Colombia',
                department VARCHAR(80) NOT NULL DEFAULT 'Antioquia',
                city VARCHAR(100) NOT NULL,
                employees INTEGER NOT NULL DEFAULT 0,
                annual_revenue DOUBLE PRECISION NOT NULL DEFAULT 0,
                contact_name VARCHAR(120) NOT NULL DEFAULT '',
                contact_email VARCHAR(150) NOT NULL DEFAULT '',
                status VARCHAR(30) NOT NULL DEFAULT 'Activa',
                created_at TIMESTAMP NOT NULL
            )
        """))
        connection.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {core_users} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id INTEGER NOT NULL REFERENCES {core_organizations}(id),
                email VARCHAR(180) NOT NULL UNIQUE,
                name VARCHAR(120) NOT NULL,
                role VARCHAR(40) NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                last_login TIMESTAMP NULL
            )
        """))
        table_sql = """
            CREATE TABLE IF NOT EXISTS {qualified_table} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key_hash VARCHAR(64) NOT NULL,
                failure_count INTEGER NOT NULL DEFAULT 0,
                window_started_at TIMESTAMP NULL,
                blocked_until TIMESTAMP NULL,
                updated_at TIMESTAMP NOT NULL
            )
        """
        audit_table_sql = """
            CREATE TABLE IF NOT EXISTS {qualified_table} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id INTEGER NOT NULL,
                user_email VARCHAR(180) NOT NULL,
                action VARCHAR(100) NOT NULL,
                entity_type VARCHAR(80) NOT NULL,
                entity_label VARCHAR(180) NOT NULL,
                detail TEXT NOT NULL DEFAULT '',
                previous_value TEXT NOT NULL DEFAULT '',
                new_value TEXT NOT NULL DEFAULT '',
                reason TEXT NOT NULL DEFAULT '',
                request_id VARCHAR(80) NOT NULL DEFAULT '',
                previous_hash VARCHAR(64) NOT NULL DEFAULT '',
                event_hash VARCHAR(64) NOT NULL DEFAULT '',
                created_at TIMESTAMP NOT NULL
            )
        """
        restore_table_sql = """
            CREATE TABLE IF NOT EXISTS {qualified_table} (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id INTEGER NOT NULL,
                backup_name VARCHAR(240) NOT NULL,
                backup_sha256 VARCHAR(64) NOT NULL DEFAULT '',
                application_version VARCHAR(30) NOT NULL DEFAULT '',
                database_backend VARCHAR(40) NOT NULL DEFAULT '',
                status VARCHAR(30) NOT NULL DEFAULT 'En ejecución',
                integrity_result VARCHAR(80) NOT NULL DEFAULT '',
                table_count INTEGER NOT NULL DEFAULT 0,
                record_summary_json TEXT NOT NULL DEFAULT '{{}}',
                checks_json TEXT NOT NULL DEFAULT '{{}}',
                notes TEXT NOT NULL DEFAULT '',
                performed_by VARCHAR(180) NOT NULL DEFAULT '',
                started_at TIMESTAMP NOT NULL,
                completed_at TIMESTAMP NULL,
                duration_ms INTEGER NOT NULL DEFAULT 0
            )
        """
        index_targets = [schema_name] if schema_name == "public" else [schema_name, "public"]
        for target_schema in index_targets:
            qualified_table = f'"{target_schema}"."login_security_states"'
            connection.execute(text(table_sql.format(qualified_table=qualified_table)))
            connection.execute(text(
                'CREATE UNIQUE INDEX IF NOT EXISTS "ix_login_security_states_key_hash" '
                f'ON {qualified_table} (key_hash)'
            ))
            connection.execute(text(
                'CREATE INDEX IF NOT EXISTS "ix_login_security_states_blocked_until" '
                f'ON {qualified_table} (blocked_until)'
            ))
            audit_table = f'"{target_schema}"."audit_events"'
            connection.execute(text(audit_table_sql.format(qualified_table=audit_table)))
            connection.execute(text(
                'CREATE INDEX IF NOT EXISTS "ix_audit_events_event_hash" '
                f'ON {audit_table} (event_hash)'
            ))
            restore_table = f'"{target_schema}"."restore_drills"'
            connection.execute(text(restore_table_sql.format(qualified_table=restore_table)))
            for index_name, column_name in (
                ("ix_restore_drills_organization_id", "organization_id"),
                ("ix_restore_drills_backup_name", "backup_name"),
                ("ix_restore_drills_status", "status"),
            ):
                connection.execute(text(
                    f'CREATE INDEX IF NOT EXISTS "{index_name}" '
                    f'ON {restore_table} ({column_name})'
                ))
        # Older staging schemas used narrower VARCHAR limits for methodology
        # metadata. Preserve complete citations, URLs and notes during seeding.
        connection.execute(text("""
            DO $$
            BEGIN
                IF to_regclass(current_schema() || '.methodology_source_documents') IS NOT NULL THEN
                    ALTER TABLE methodology_source_documents ALTER COLUMN title TYPE TEXT;
                    ALTER TABLE methodology_source_documents ALTER COLUMN issuing_body TYPE TEXT;
                    ALTER TABLE methodology_source_documents ALTER COLUMN document_type TYPE TEXT;
                    ALTER TABLE methodology_source_documents ALTER COLUMN jurisdiction TYPE TEXT;
                    ALTER TABLE methodology_source_documents ALTER COLUMN source_url TYPE TEXT;
                    ALTER TABLE methodology_source_documents ALTER COLUMN status TYPE TEXT;
                END IF;
            END $$;
        """))

init_db()
if settings.seed_demo:
    # Preserve the demo entry point even when a prior deploy created the
    # organization but stopped before seeding users.
    with SessionLocal() as session:
        organization = session.scalar(select(Organization).limit(1))
        has_user = session.scalar(select(AppUser.id).limit(1))
        if organization and not has_user:
            demo_password = hash_password("Demo2026!")
            session.add_all([
                AppUser(organization_id=organization.id, email="admin@calculatuhuella.local", name="Laura Méndez", role="Administrador", password_hash=demo_password),
                AppUser(organization_id=organization.id, email="consultor@calculatuhuella.local", name="Carlos Uribe", role="Consultor", password_hash=demo_password),
                AppUser(organization_id=organization.id, email="cliente@calculatuhuella.local", name="Ana Martínez", role="Cliente", password_hash=demo_password),
                AppUser(organization_id=organization.id, email="revisor@calculatuhuella.local", name="María Fernández", role="Revisor", password_hash=demo_password),
                AppUser(organization_id=organization.id, email="verificador@calculatuhuella.local", name="Andrés Salazar", role="Verificador", password_hash=demo_password),
            ])
            session.commit()
print("Esquema e inicialización verificados.")
PYCODE
if [ "${DEPLOYMENT_STRICT:-false}" = "true" ]; then
  "$PY" scripts/check_ready.py
else
  echo "Certificación externa diferida: DEPLOYMENT_STRICT=false; consultar /api/ready." >&2
fi

exec "$PY" -m uvicorn app.main:app \
  --host "$HOST" \
  --port "$PORT" \
  --workers "${WEB_CONCURRENCY:-1}" \
  --proxy-headers \
  --forwarded-allow-ips "${FORWARDED_ALLOW_IPS:-*}" \
  --no-access-log
