create extension if not exists pgcrypto;

create table if not exists plants (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists employees (id uuid primary key default gen_random_uuid(), plant_id uuid references plants(id), display_name text not null, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists scheduled_activities (id uuid primary key default gen_random_uuid(), plant_id uuid not null references plants(id), title text not null, process text, planned_start timestamptz not null, planned_end timestamptz, status text not null default 'planned' check(status in('planned','running','done','delayed','missed','rescheduled')), created_at timestamptz not null default now());
create table if not exists activities (id uuid primary key default gen_random_uuid(), plant_id uuid not null references plants(id), scheduled_activity_id uuid references scheduled_activities(id), title text not null, process text, started_at timestamptz not null, ended_at timestamptz, quantity numeric, unit text, notes text, created_at timestamptz not null default now(), check(ended_at is null or ended_at>=started_at));
create table if not exists activity_workers (activity_id uuid not null references activities(id) on delete cascade, employee_id uuid not null references employees(id), primary key(activity_id,employee_id));
create table if not exists equipment (id uuid primary key default gen_random_uuid(), plant_id uuid not null references plants(id), code text not null, name text not null, status text not null default 'available' check(status in('available','attention','stopped','maintenance')), unique(plant_id,code));
create table if not exists incidents (id uuid primary key default gen_random_uuid(), plant_id uuid not null references plants(id), equipment_id uuid references equipment(id), severity text not null default 'medium' check(severity in('low','medium','high')), title text not null, description text, opened_at timestamptz not null default now(), closed_at timestamptz, check(closed_at is null or closed_at>=opened_at));
