import type { Metadata } from "next";
import Link from "next/link";
import { runtimeLinks } from "@/lib/runtime-links";

export const metadata: Metadata = {
  title: "Acceso a plataformas Greenatics",
  description: "Centro de acceso a las plataformas Greenatics: OPS, Calcula tu Huella, GREENATICS Red, AGROWAY y SANA.",
  alternates: { canonical: "/acceso/" },
};

const environments: Array<{ code: string; name: string; status: string; copy: string; publicHref: string; publicCta: string; access: string; accessHref: string; demoHref?: string }> = [
  { code: "OPS", name: "GREENATICS OPS", status: "Demostración pública disponible", copy: "La demostración permite recorrer bitácora, recepción, procesos, mantenimiento, inventarios e indicadores con datos ilustrativos. Los entornos de operación se configuran por organización, planta y rol.", publicHref: "/app/", publicCta: "Abrir demostración", access: "Preparar entorno real", accessHref: "/contacto/?interes=greenatics-ops", demoHref: "/app/#estacion" },
  { code: "CO₂", name: "Calcula tu Huella", status: "Estimador público disponible", copy: "Explora escenarios de emisiones y conoce la plataforma completa para inventarios, fuentes, cargas CSV/XLSX, validación, evidencias, historial y reportes climáticos.", publicHref: "/huella/", publicCta: "Abrir landing de Huella", access: "Preparar entorno real", accessHref: "/contacto/?interes=calcula-tu-huella", demoHref: "/huella/#calculadora" },
  { code: "RED", name: "GREENATICS Red", status: "Estación pública navegable", copy: "Recorre una estación territorial con Proyecto 360, generadores, rutas, FIELD, QA/QC, PMIRS, indicadores, evidencias y coordinación. La demo ya permite entender el flujo; el entorno productivo se conecta después a la organización, sus roles y sus datos.", publicHref: "/red/app/", publicCta: "Explorar estación Red", access: "Preparar entorno real", accessHref: "/contacto/?interes=greenatics-red", demoHref: "/red/app/" },
  { code: "AG", name: "AGROWAY", status: "Demo navegable disponible", copy: "Aplicación de trazabilidad agrícola para registrar productor, finca, lote, ciclo, diagnóstico, plan, abastecimiento, ejecución, evidencia, seguimiento y cosecha.", publicHref: "/agroway/", publicCta: "Conocer AGROWAY", access: "Diseñar implementación", accessHref: "/contacto/?interes=agroway", demoHref: "/agroway/app/" },
  { code: "SANA", name: "SANA", status: "Demo navegable disponible", copy: "Ecosistema para estructurar y acompañar inversión en proyectos productivos con datos de AGROWAY, ciencia Greenatics, soluciones Wondergreen y seguimiento de campo.", publicHref: "/sana/", publicCta: "Conocer SANA", access: "Diseñar implementación", accessHref: "/contacto/?interes=sana", demoHref: "/sana/app/" },
];

const isLocalRuntime = (url: string) => /localhost|127\.0\.0\.1/.test(url);

export default function AccessPage() {
  return (
    <>
      <section className="access-v4-hero"><div className="container"><span className="eyebrow eyebrow--light">Acceso a entornos Greenatics</span><h1>Entra directamente a una demo. Configura tu entorno cuando estés listo.</h1><p className="lead">OPS, Calcula tu Huella, GREENATICS Red, AGROWAY y SANA tienen una experiencia pública para recorrer sus módulos y entender su alcance. Cuando el trabajo requiere datos propios, la misma lógica se configura por organización, roles, permisos y proyecto.</p><div className="button-row"><Link className="button button--light" href="#entornos-disponibles">Ver entornos disponibles</Link><Link className="button button--outline-light" href="/plataforma/">Abrir Centro Greenatics</Link></div></div></section>

      <section className="access-v4-environments" id="entornos-disponibles" aria-labelledby="access-environments-title"><div className="container"><div className="digital-v4-heading"><div><span className="eyebrow">Entornos disponibles</span><h2 id="access-environments-title">Primero la landing. Después la entrada operativa.</h2></div><p>OPS controla la planta; Huella organiza la gestión climática; Red coordina territorio y PMIRS; AGROWAY registra la trazabilidad agrícola en campo; SANA articula esa información con la ciencia Greenatics, las soluciones Wondergreen y los proyectos productivos. Cada tarjeta deja claro si puedes entrar directamente a un runtime o a una experiencia navegable.</p></div><div className="access-v4-environments__grid">{environments.map((environment) => { const runtimeHref = environment.code === "OPS" ? runtimeLinks.opsApp : environment.code === "CO₂" ? runtimeLinks.huella : environment.code === "RED" ? runtimeLinks.red : ""; const runtimeState = runtimeHref ? isLocalRuntime(runtimeHref) ? "Runtime local disponible" : "Runtime conectado" : environment.demoHref ? "Experiencia navegable disponible" : environment.status; const demoLabel = environment.code === "OPS" ? "Explorar estación demo" : environment.code === "CO₂" ? "Explorar estimador" : environment.code === "RED" ? "Entrar a la estación demo" : "Entrar como usuario demo"; return <article key={environment.code}><span>{environment.code}</span><small>{runtimeState}</small><h3>{environment.name}</h3><p>{environment.copy}</p><div className="button-row"><Link className="button button--dark" href={environment.publicHref} aria-label={`${environment.publicCta}: ${environment.name}`}>{environment.publicCta}</Link>{runtimeHref ? <><a className="button button--primary" href={runtimeHref} target={/^https?:\/\//.test(runtimeHref) ? "_blank" : undefined} rel={/^https?:\/\//.test(runtimeHref) ? "noopener noreferrer" : undefined} aria-label={`Entrar a ${environment.name}`}>Entrar al entorno ↗</a>{environment.demoHref && <Link className="button button--ghost" href={environment.demoHref} aria-label={`${demoLabel}: ${environment.name}`}>{demoLabel} →</Link>}</> : environment.demoHref ? <Link className="button button--primary" href={environment.demoHref} aria-label={`${demoLabel}: ${environment.name}`}>{demoLabel} ↗</Link> : <Link className="button button--ghost" href={environment.accessHref} aria-label={`${environment.access}: ${environment.name}`}>{environment.access}</Link>}</div></article>; })}</div></div></section>

      <section className="access-v4-process"><div className="container"><div><span className="eyebrow eyebrow--light">Cómo se habilita</span><h2>Un acceso operativo claro, seguro y por organización.</h2></div><ol><li><span>01</span><strong>Alcance</strong><p>Organización, plantas o proyectos, usuarios, módulos y decisiones que debe soportar.</p></li><li><span>02</span><strong>Configuración</strong><p>Catálogos, roles, permisos, flujos, datos iniciales, indicadores y entregables.</p></li><li><span>03</span><strong>Adopción</strong><p>Formación, acompañamiento, revisión de calidad y mejora de la captura.</p></li><li><span>04</span><strong>Continuidad</strong><p>Soporte, ajustes, nuevos módulos y gobierno de reportes según el contrato.</p></li></ol><Link className="button button--light" href="/plataforma/usuarios/">Administrar usuarios y roles →</Link></div></section>

      <section className="access-v4-truth"><div className="container access-v4-truth__grid"><div><span className="eyebrow">Acceso operativo seguro</span><h2>Cada entorno protege sus datos, sus usuarios y sus responsabilidades.</h2></div><div><p>Las demos públicas funcionan con datos ilustrativos y no requieren contraseñas. Cuando una organización trabaja con información propia, el acceso se habilita con identidad, roles, permisos y trazabilidad; no usamos credenciales genéricas ni presentamos como conectado un sistema que aún no forma parte de la implementación.</p><Link href="/contacto/?interes=plataformas">Definir una implementación segura →</Link></div></div></section>
    </>
  );
}
