import type { Metadata } from "next";
import Link from "next/link";
import { ProductCard } from "@/components/product-card";
import { featuredProducts } from "@/data/products";

export const metadata: Metadata = { alternates: { canonical: "/" } };

const doors = [
  { kicker: "Producto agrícola", title: "Wondergreen", copy: "Acondicionadores, fertilizantes organominerales sólidos y líquidos, bioinsumos, guías por cultivo y referencias con precio público reconciliado.", href: "/wondergreen/", cta: "Explorar productos" },
  { kicker: "Territorios", title: "Municipios y ESP", copy: "PGIRS, prefactibilidad, rutas selectivas, motocarguero, plantas, rehabilitación, operación y trazabilidad para convertir planeación en capacidad real.", href: "/municipios/", cta: "Ver ruta municipal" },
  { kicker: "Generadores", title: "Empresas", copy: "PMIRS, caracterización, separación, recolección, tratamiento, infraestructura y evidencia para corrientes orgánicas empresariales.", href: "/empresas/", cta: "Ver soluciones empresariales" },
  { kicker: "Ingeniería + biología", title: "Plantas y tecnología", copy: "Compostaje, digestión anaerobia multietapa, biogás, biol, fertilizantes y operación basada en parámetros, mantenimiento y datos.", href: "/tecnologia/", cta: "Conocer la tecnología" },
];

const chain = [
  ["01", "Entender", "Generadores, corriente, volumen, calidad, logística, infraestructura y restricciones."],
  ["02", "Separar y recolectar", "Protocolos, rutas selectivas, microrrutas, motocarguero y captura de datos."],
  ["03", "Transformar", "Compostaje, digestión anaerobia u otras rutas definidas por caracterización y escala."],
  ["04", "Operar", "Personal, POE, mantenimiento, control de calidad, lotes, inventarios y gestión diaria."],
  ["05", "Crear valor", "Compost, biol, fertilizantes organominerales, biogás y otros destinos técnicamente validados."],
  ["06", "Medir y mejorar", "GREENATICS OPS conecta operación, evidencia, indicadores y publicación controlada de impacto."],
];

const knowledge = [
  { kicker: "Diagnóstico", title: "Deficiencias nutricionales", copy: "Una guía para leer síntomas en cinco cultivos antes de asumir que todo se resuelve aplicando fertilizante.", href: "/biblioteca/guia-deficiencias/" },
  { kicker: "Uso en campo", title: "Manual Wondergreen", copy: "Checklist previo, vía operativa, errores a evitar y seguimiento para ejecutar mejor una recomendación.", href: "/biblioteca/manual-uso-wondergreen/" },
  { kicker: "Huertas", title: "Cultivar también es aprender", copy: "Ruta para huertas urbanas, escolares y comunitarias desde el suelo hasta la cosecha y el aprendizaje circular.", href: "/biblioteca/huertas/" },
];

export default function Home() {
  return (
    <>
      <section className="hero hero--v2"><div className="container hero-grid"><div className="hero-copy"><div className="hero-brand-lockup"><img className="official-logo" src="/brand/greenatics-horizontal.webp" alt="Greenatics" width="360" height="66" /></div><span className="eyebrow">Economía circular aplicada · Colombia</span><h1>Convertimos residuos orgánicos en <em>sistemas que devuelven valor al territorio y al suelo.</em></h1><p className="lead">Greenatics conecta planeación, recolección selectiva, plantas de aprovechamiento, biotecnología, operación, fertilizantes Wondergreen y datos. No trabajamos una etapa aislada: diseñamos cómo el residuo entra, se transforma, se controla y vuelve al ciclo productivo.</p><div className="button-row"><Link className="button button--primary" href="/wondergreen/">Ver Wondergreen</Link><Link className="button button--light" href="/diagnostico/">¿Qué solución necesito?</Link></div></div><div className="cycle-visual" aria-label="Ciclo Greenatics: residuo, transformación, producto, suelo e impacto"><div className="cycle-center"><img src="/brand/greenatics-symbol.svg" alt="" aria-hidden="true" /></div><div className="cycle-node node-1"><strong>01</strong><span>Residuo</span></div><div className="cycle-node node-2"><strong>02</strong><span>Bioproceso</span></div><div className="cycle-node node-3"><strong>03</strong><span>Recurso</span></div><div className="cycle-node node-4"><strong>04</strong><span>Suelo</span></div><div className="cycle-node node-5"><strong>05</strong><span>Datos</span></div></div></div></section>

      <section className="home-definition"><div className="container home-definition-grid"><div><span className="eyebrow">Qué es Greenatics</span><h2>Una plataforma de aprovechamiento orgánico con una cadena completa de servicios, tecnología y producto.</h2></div><div><p>No somos únicamente una empresa de fertilizantes y tampoco únicamente una empresa de residuos. La propuesta Greenatics une ambas puntas: gestionar biomasa residual de manera técnicamente controlada y convertir parte de ese proceso en recursos que puedan retornar a sistemas productivos, con información suficiente para operar y aprender.</p><Link href="/nosotros/">Conocer Greenatics →</Link></div></div></section>

      <section className="home-doors" id="soluciones"><div className="container"><div className="section-heading"><span className="eyebrow">Cuatro puertas de entrada</span><h2>Empieza por lo que necesitas resolver hoy.</h2></div><div className="home-door-grid">{doors.map((item)=><article key={item.title}><span className="eyebrow">{item.kicker}</span><h3>{item.title}</h3><p>{item.copy}</p><Link href={item.href}>{item.cta} →</Link></article>)}</div><div className="diagnostic-entry"><div><strong>¿Tu necesidad cruza varias categorías?</strong><span>El diagnóstico Greenatics enruta el problema antes de recomendar producto, planta o servicio.</span></div><Link className="button button--dark" href="/diagnostico/">Hacer diagnóstico</Link></div></div></section>

      <section className="home-chain"><div className="container"><div className="section-heading"><span className="eyebrow eyebrow--light">Cómo cerramos el ciclo</span><h2>Del generador al dato y del dato a la mejora.</h2><p>La propuesta se vuelve concreta cuando cada eslabón tiene una función y una salida verificable.</p></div><div className="home-chain-grid">{chain.map(([number,title,copy])=><article key={number}><span>{number}</span><strong>{title}</strong><p>{copy}</p></article>)}</div><div className="home-chain-action"><Link className="button button--light" href="/servicios/">Ver los servicios detrás de cada etapa</Link></div></div></section>

      <section className="wondergreen-band wondergreen-band--v2"><div className="container wg-intro"><div className="wg-brand-column"><span className="eyebrow eyebrow--light">Producto inmediato · Wondergreen Nutrients</span><div className="wondergreen-official-lockup"><img className="official-logo" src="/brand/wondergreen-nutrients.webp" alt="Wondergreen Nutrients" width="420" height="221" /></div><h2>El ciclo también necesita una salida comercial clara.</h2></div><div><p>Wondergreen reúne compost/acondicionadores, fertilizantes organominerales sólidos y líquidos y un portafolio técnico de bioinsumos. La selección se organiza por suelo, crecimiento, balance, floración, producción y manejo integrado.</p><div className="button-row"><Link className="button button--light" href="/wondergreen/">Ver portafolio completo</Link><Link className="button button--outline-light" href="/wondergreen/cultivos/">Buscar por cultivo</Link></div></div></div><div className="container product-grid">{featuredProducts.map((product)=><ProductCard key={product.slug} product={product} />)}</div><div className="container band-cta"><Link className="button button--light" href="/wondergreen/cotizador/">Cotizar referencias reconciliadas</Link></div></section>

      <section className="home-public-system"><div className="container home-public-grid"><div><span className="eyebrow">Municipios y ESP</span><h2>Un PGIRS no aprovecha residuos por sí solo. La ejecución necesita una cadena.</h2><p>Greenatics puede intervenir desde diagnóstico y prefactibilidad hasta ruta selectiva, motocarguero, ingeniería, construcción/rehabilitación, puesta en marcha, operación y datos. El concepto de Parque Ambiental permite integrar esas capas en una arquitectura territorial modular cuando el proyecto lo justifica.</p><div className="button-row"><Link className="button button--dark" href="/municipios/">Ver solución municipal</Link><Link className="button button--ghost" href="/servicios/">Ver portafolio</Link></div></div><div className="home-public-stack">{["PGIRS + diagnóstico","Prefactibilidad / factibilidad","Ruta selectiva + motocarguero","Planta / rehabilitación","Operación + mantenimiento","GREENATICS OPS + indicadores"].map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><strong>{item}</strong></div>)}</div></div></section>

      <section className="home-science"><div className="container home-science-grid"><div><span className="eyebrow eyebrow--light">Ciencia aplicada</span><h2>Digestión anaerobia multietapa, compostaje y cierre de ciclos biogeoquímicos.</h2><p>La documentación de proyectos Greenatics–Universidad de Antioquia describe sistemas que separan hidrólisis/acidogénesis y metanogénesis, integran recirculación de corrientes y combinan aprovechamiento material y energético. Greenatics ha trabajado con acompañamiento del Grupo Interdisciplinario de Estudios Moleculares —GIEM— de la UdeA.</p><Link className="button button--light" href="/tecnologia/">Entender la tecnología</Link></div><div className="home-science-flow"><span>FORSU separado</span><b>→</b><span>Compostaje / digestión</span><b>→</b><span>Compost · biol · fertilizantes · biogás</span><b>→</b><span>Suelo + energía + datos</span></div></div></section>

      <section className="knowledge-section"><div className="container"><div className="section-heading"><span className="eyebrow">Conocimiento que se usa</span><h2>Catálogos y guías deben ayudar a decidir, no vivir escondidos en una carpeta.</h2><p>El conocimiento construido en Greenatics Marketing Studio se convierte gradualmente en recursos web navegables y conectados a productos, cultivos y diagnósticos.</p></div><div className="knowledge-card-grid">{knowledge.map((item)=><article key={item.title}><span className="knowledge-card-kicker">{item.kicker}</span><h3>{item.title}</h3><p>{item.copy}</p><Link className="knowledge-inline-link" href={item.href}>Abrir recurso →</Link></article>)}</div><div className="knowledge-actions"><Link className="button button--ghost" href="/biblioteca/">Explorar biblioteca técnica</Link></div></div></section>

      <section className="impact-section" id="impacto"><div className="container impact-grid"><div><span className="eyebrow">Impacto conectado a la operación</span><h2>Preferimos un dato pendiente a una cifra espectacular sin trazabilidad.</h2><p>GREENATICS OPS está diseñado para conectar generador, ruta, recepción, proceso, producto, inventario y destino. La capa pública solo mostrará indicadores conciliados, aprobados, fechados y con metodología cuando corresponda.</p><div className="button-row"><Link className="button button--primary" href="/impacto/">Ver modelo de impacto</Link><Link className="button button--ghost" href="/proyectos/">Ver proyectos</Link></div></div><div className="impact-console"><div className="console-top"><span>GREENATICS · IMPACTO</span><span className="live-dot">publicación gobernada</span></div><div className="metric-skeleton"><span>Residuos aprovechados</span><strong>—</strong><small>Pendiente corte conciliado</small></div><div className="metric-skeleton"><span>Producto generado</span><strong>—</strong><small>Fuente futura: GREENATICS OPS</small></div><div className="metric-skeleton"><span>Indicadores ambientales</span><strong>—</strong><small>Metodología + aprobación requeridas</small></div></div></div></section>

      <section className="closing-cta"><div className="container closing-inner"><div><span className="eyebrow">Greenatics</span><h2>¿Tienes un residuo, un cultivo, una planta o un territorio por transformar?</h2></div><div className="button-row"><Link className="button button--dark" href="/contacto/">Hablemos</Link><Link className="button button--ghost" href="/diagnostico/">Empezar diagnóstico</Link></div></div></section>
    </>
  );
}
