"use client";

import { useState } from "react";
import { useCommercialStore } from "@/components/commercial-store";
import { useExpenseStore } from "@/components/expense-store";
import { useOpsStore } from "@/components/ops-store";
import { useSettlementStore } from "@/components/settlement-store";
import { canRecordSettlement,remainingAmount,settledAmount,settlementMethodLabel,settlementStatus,settlementStatusLabel,type SettlementMethod } from "@/lib/settlement-domain";
import { bogotaDateKey } from "@/lib/time";

const cop=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
type FormProps={sourceId:string;remainingCop:number;kind:"collection"|"payment"};

function SettlementForm({sourceId,remainingCop,kind}:FormProps){
  const {recordCollection,recordPayment}=useSettlementStore();const [amount,setAmount]=useState("");const [date,setDate]=useState(()=>bogotaDateKey(new Date()));const [method,setMethod]=useState<SettlementMethod>("transfer");const [reference,setReference]=useState("");const [feedback,setFeedback]=useState("");const [busy,setBusy]=useState(false);
  async function save(){if(busy)return;setBusy(true);setFeedback("");const fn=kind==="collection"?recordCollection:recordPayment;const result=await fn({sourceId,amountCop:Number(amount),occurredOn:date,method,reference});if(!result.ok){setFeedback(result.error);setBusy(false);return;}setAmount("");setReference("");setFeedback(kind==="collection"?"Recaudo registrado.":"Pago registrado.");setBusy(false);}
  return <div className="mt-3 grid gap-2 rounded-lg bg-[var(--surface-soft)] p-3 sm:grid-cols-4"><label className="grid gap-1 text-[10px] font-bold text-[var(--muted)]">Monto<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm" inputMode="numeric" value={amount} onChange={(e)=>setAmount(e.target.value)} placeholder={String(Math.round(remainingCop))} disabled={busy}/></label><label className="grid gap-1 text-[10px] font-bold text-[var(--muted)]">Fecha<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm" type="date" value={date} onChange={(e)=>setDate(e.target.value)} disabled={busy}/></label><label className="grid gap-1 text-[10px] font-bold text-[var(--muted)]">Método<select className="min-h-10 rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={method} onChange={(e)=>setMethod(e.target.value as SettlementMethod)} disabled={busy}>{Object.entries(settlementMethodLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-1 text-[10px] font-bold text-[var(--muted)]">Referencia<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm" value={reference} onChange={(e)=>setReference(e.target.value)} placeholder="Opcional" disabled={busy}/></label><div className="flex items-center gap-3 sm:col-span-4"><button className="button primary" type="button" onClick={()=>void save()} disabled={busy}>{busy?(kind==="collection"?"Registrando recaudo…":"Registrando pago…"):(kind==="collection"?"Registrar recaudo":"Registrar pago")}</button>{feedback&&<span role="status" className="text-xs text-[var(--muted)]">{feedback}</span>}</div></div>;
}

export function CashView(){
  const {sales}=useCommercialStore();const {expenses}=useExpenseStore();const {settlements}=useSettlementStore();const {backend,access}=useOpsStore();const totalCollected=settlements.filter((x)=>x.kind==="collection").reduce((s,x)=>s+x.amountCop,0);const totalPaid=settlements.filter((x)=>x.kind==="payment").reduce((s,x)=>s+x.amountCop,0);
  return <><header className="page-header"><div><p className="eyebrow">Dinero real registrado</p><h1>Caja · recaudos y pagos</h1><p className="lede">Movimientos de dinero separados de facturación y gastos. El flujo registrado no equivale a utilidad ni saldo bancario.</p></div></header>
    <section className="metrics-grid"><div className="metric-block"><span>Recaudado</span><strong>{cop.format(totalCollected)}</strong><small>movimientos registrados</small></div><div className="metric-block"><span>Pagado</span><strong>{cop.format(totalPaid)}</strong><small>movimientos registrados</small></div><div className="metric-block"><span>Flujo registrado</span><strong>{cop.format(totalCollected-totalPaid)}</strong><small>recaudos − pagos; no utilidad</small></div></section>
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="panel"><div className="section-head"><div><p className="eyebrow">Cuentas por cobrar operativas</p><h2>Ventas</h2></div></div><div className="grid gap-3">{sales.length?sales.map((sale)=>{const settled=settledAmount(settlements,"collection",sale.id);const remaining=remainingAmount(sale.totalCop,settled);const status=settlementStatus(sale.totalCop,settled);const canWrite=backend.mode!=="supabase"||canRecordSettlement(access,sale.plantId);return <article className="rounded-xl border border-[var(--line)] p-4" key={sale.id}><div className="flex justify-between gap-3"><div><strong>{sale.customerName}</strong><span className="block text-xs text-[var(--muted)]">{sale.productName} · {sale.lotCode}</span></div><span className="status-pill status-planned">{settlementStatusLabel[status]}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><span className="quiet">Venta</span><strong className="block">{cop.format(sale.totalCop)}</strong></div><div><span className="quiet">Recaudado</span><strong className="block">{cop.format(settled)}</strong></div><div><span className="quiet">Pendiente</span><strong className="block">{cop.format(remaining)}</strong></div></div>{remaining>0&&canWrite&&<SettlementForm sourceId={sale.id} remainingCop={remaining} kind="collection"/>}{remaining>0&&!canWrite&&<p className="quiet mt-3">Solo lectura. Registrar recaudos requiere rol supervisor, administrador o director en esta planta.</p>}</article>}):<p className="quiet">Sin ventas registradas.</p>}</div></section>
      <section className="panel"><div className="section-head"><div><p className="eyebrow">Cuentas por pagar operativas</p><h2>Compras y gastos</h2></div></div><div className="grid gap-3">{expenses.length?expenses.map((expense)=>{const settled=settledAmount(settlements,"payment",expense.id);const remaining=remainingAmount(expense.amountCop,settled);const status=settlementStatus(expense.amountCop,settled);const canWrite=backend.mode!=="supabase"||canRecordSettlement(access,expense.plantId);return <article className="rounded-xl border border-[var(--line)] p-4" key={expense.id}><div className="flex justify-between gap-3"><div><strong>{expense.supplierName}</strong><span className="block text-xs text-[var(--muted)]">{expense.concept} · {expense.plant}</span></div><span className="status-pill status-planned">{settlementStatusLabel[status]}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><span className="quiet">Registrado</span><strong className="block">{cop.format(expense.amountCop)}</strong></div><div><span className="quiet">Pagado</span><strong className="block">{cop.format(settled)}</strong></div><div><span className="quiet">Pendiente</span><strong className="block">{cop.format(remaining)}</strong></div></div>{remaining>0&&canWrite&&<SettlementForm sourceId={expense.id} remainingCop={remaining} kind="payment"/>}{remaining>0&&!canWrite&&<p className="quiet mt-3">Solo lectura. Registrar pagos requiere rol supervisor, administrador o director en esta planta.</p>}</article>}):<p className="quiet">Sin compras/gastos registrados.</p>}</div></section>
    </div></>;
}
