"use client";

import Link from "next/link";
import { useMemo,useState } from "react";
import { useOpsStore } from "@/components/ops-store";
import { usePurchaseRequestStore } from "@/components/purchase-request-store";
import { expenseCategoryLabel } from "@/lib/expense-domain";
import { canManagePurchaseRequest,purchaseRequestStatusLabel,type PurchaseRequestRecord,type PurchaseRequestStatus } from "@/lib/purchase-request-domain";
import { bogotaDateKey } from "@/lib/time";

const cop=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const dateFmt=new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Bogota"});
function statusClass(status:PurchaseRequestStatus){return status==="approved"||status==="fulfilled"?"status-normal":status==="rejected"?"status-critical":"status-planned";}

function RequestCard({request}:{request:PurchaseRequestRecord}){
  const {backend,access}=useOpsStore();
  const {events,approveRequest,rejectRequest,fulfillRequest}=usePurchaseRequestStore();
  const canManage=backend.mode!=="supabase"||canManagePurchaseRequest(access,request.plantId);
  const [actor,setActor]=useState("");const [decisionNote,setDecisionNote]=useState("");const [supplierName,setSupplierName]=useState(request.suggestedSupplier??"");const [actualAmount,setActualAmount]=useState("");const [documentDate,setDocumentDate]=useState(()=>bogotaDateKey(new Date()));const [documentRef,setDocumentRef]=useState("");const [feedback,setFeedback]=useState("");const [busy,setBusy]=useState(false);
  const requestEvents=events.filter((item)=>item.requestId===request.id).sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime());
  async function run(action:()=>Promise<{ok:true;id:string}|{ok:false;error:string}>,success:string){if(busy)return;setBusy(true);setFeedback("");const result=await action();setFeedback(result.ok?success:result.error);setBusy(false);}
  function approve(){void run(()=>approveRequest(request.id,actor,decisionNote),"Solicitud aprobada.");}
  function reject(){void run(()=>rejectRequest(request.id,actor,decisionNote),"Solicitud rechazada.");}
  function fulfill(){void run(()=>fulfillRequest({requestId:request.id,actor,supplierName,actualAmountCop:Number(actualAmount),documentDate,documentRef,note:decisionNote}),"Compra real registrada y solicitud cumplida.");}

  return <article className="rounded-xl border border-[var(--line)] p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className={`status-pill ${statusClass(request.status)}`}>{purchaseRequestStatusLabel[request.status]}</span><strong className="text-sm">{request.concept}</strong></div><span className="mt-1 block text-xs text-[var(--muted)]">{request.plant} · solicita {request.requestedBy} · {expenseCategoryLabel[request.category]}</span></div><div className="text-right"><span className="quiet">Estimado</span><strong className="block text-lg">{cop.format(request.estimatedAmountCop)}</strong></div></div>
    <p className="mt-3 text-xs text-[var(--muted)]">{request.justification}</p>
    <div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 border-t border-[var(--line)] pt-3 text-[11px] text-[var(--muted)]"><span>Enviada: <strong className="text-[var(--ink)]">{dateFmt.format(new Date(request.requestedAt))}</strong></span>{request.neededBy&&<span>Necesaria: <strong className="text-[var(--ink)]">{request.neededBy}</strong></span>}{request.suggestedSupplier&&<span>Proveedor sugerido: <strong className="text-[var(--ink)]">{request.suggestedSupplier}</strong></span>}{request.equipmentName&&<span>Equipo: <strong className="text-[var(--ink)]">{request.equipmentName}</strong></span>}{request.expenseId&&<span>Gasto real: <strong className="text-[var(--ink)]">{request.expenseId.slice(0,8)}…</strong></span>}</div>

    {request.status==="submitted"&&canManage&&<div className="mt-4 grid gap-3 rounded-xl bg-[var(--surface-soft)] p-4 md:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Responsable de decisión<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm text-[var(--ink)]" value={actor} onChange={(event)=>setActor(event.target.value)} placeholder="Nombre responsable" disabled={busy}/></label><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Nota / razón<textarea className="min-h-20 rounded-lg border border-[var(--line)] p-3 text-sm text-[var(--ink)]" value={decisionNote} onChange={(event)=>setDecisionNote(event.target.value)} placeholder="Opcional al aprobar; obligatoria al rechazar" disabled={busy}/></label><div className="flex flex-wrap gap-2 md:col-span-2"><button className="button primary" type="button" onClick={approve} disabled={busy}>{busy?"Procesando…":"Aprobar solicitud"}</button><button className="button secondary" type="button" onClick={reject} disabled={busy}>Rechazar</button></div></div>}

    {request.status==="approved"&&canManage&&<div className="mt-4 rounded-xl bg-[var(--green-soft)] p-4"><div className="section-head"><div><strong className="text-sm">Convertir a compra real</strong><p className="quiet">El monto real puede ser diferente del estimado.</p></div></div><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Responsable<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm text-[var(--ink)]" value={actor} onChange={(event)=>setActor(event.target.value)} placeholder="Quién registra/cierra" disabled={busy}/></label><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Proveedor real<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm text-[var(--ink)]" value={supplierName} onChange={(event)=>setSupplierName(event.target.value)} placeholder="Proveedor definitivo" disabled={busy}/></label><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Monto real COP<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm text-[var(--ink)]" inputMode="numeric" value={actualAmount} onChange={(event)=>setActualAmount(event.target.value)} placeholder="Ej. 185000" disabled={busy}/></label><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Fecha documento<input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm text-[var(--ink)]" type="date" value={documentDate} onChange={(event)=>setDocumentDate(event.target.value)} disabled={busy}/></label><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Factura / soporte <span className="font-normal">(opcional)</span><input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm text-[var(--ink)]" value={documentRef} onChange={(event)=>setDocumentRef(event.target.value)} placeholder="Ej. FV-1024" disabled={busy}/></label><label className="grid gap-1 text-xs font-bold text-[var(--muted)]">Nota <span className="font-normal">(opcional)</span><input className="min-h-10 rounded-lg border border-[var(--line)] px-3 text-sm text-[var(--ink)]" value={decisionNote} onChange={(event)=>setDecisionNote(event.target.value)} placeholder="Detalle de cierre" disabled={busy}/></label><div className="md:col-span-2"><button className="button primary" type="button" onClick={fulfill} disabled={busy}>{busy?"Registrando compra…":"Registrar compra real y cerrar solicitud"}</button></div></div></div>}

    {(request.status==="submitted"||request.status==="approved")&&!canManage&&<p className="quiet mt-4 rounded-xl bg-[var(--surface-soft)] p-3">Solo supervisión o dirección autorizada de esta planta puede {request.status==="submitted"?"aprobar o rechazar":"registrar la compra real"}.</p>}

    {feedback&&<p role="status" className="mt-3 text-xs font-semibold text-[var(--green-dark)]">{feedback}</p>}
    <details className="mt-4 border-t border-[var(--line)] pt-3"><summary className="cursor-pointer text-xs font-semibold text-[var(--muted)]">Historial · {requestEvents.length} evento{requestEvents.length===1?"":"s"}</summary><div className="mt-2 grid gap-2">{requestEvents.map((event)=><div className="rounded-lg bg-[var(--surface-soft)] p-3 text-xs" key={event.id}><strong>{purchaseRequestStatusLabel[event.kind]}</strong><span className="ml-2 text-[var(--muted)]">{event.actor} · {dateFmt.format(new Date(event.at))}</span>{event.actualAmountCop!==undefined&&<span className="mt-1 block text-[var(--muted)]">Monto real: {cop.format(event.actualAmountCop)}</span>}{event.note&&<span className="mt-1 block text-[var(--muted)]">{event.note}</span>}</div>)}</div></details>
  </article>;
}

export function PurchaseRequestsView(){
  const {requests}=usePurchaseRequestStore();const [status,setStatus]=useState<"all"|PurchaseRequestStatus>("all");const [plantId,setPlantId]=useState("all");const filtered=useMemo(()=>requests.filter((item)=>(status==="all"||item.status===status)&&(plantId==="all"||item.plantId===plantId)),[requests,status,plantId]);const pending=requests.filter((item)=>item.status==="submitted").length;const approved=requests.filter((item)=>item.status==="approved").length;
  return <><header className="page-header"><div><p className="eyebrow">Compras · control previo</p><h1>Solicitudes</h1><p className="lede">Necesidad → decisión → compra real. Las estimaciones nunca entran como gasto hasta cerrar una solicitud aprobada.</p></div><div className="header-actions"><Link className="button secondary" href="/expenses">Ver compras/gastos</Link><Link className="button primary" href="/purchases/new">Nueva solicitud</Link></div></header>
    <section className="metrics-grid" aria-label="Indicadores de solicitudes"><div className="metric-block"><span>Pendientes</span><strong>{pending}</strong><small>esperan decisión</small></div><div className="metric-block"><span>Aprobadas</span><strong>{approved}</strong><small>esperan compra real</small></div><div className="metric-block"><span>Cumplidas</span><strong>{requests.filter((item)=>item.status==="fulfilled").length}</strong><small>ya enlazadas a gasto</small></div><div className="metric-block"><span>Rechazadas</span><strong>{requests.filter((item)=>item.status==="rejected").length}</strong><small>cerradas sin compra</small></div></section>
    <section className="panel mb-4"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Estado<select className="min-h-10 rounded-lg border border-[var(--line)] bg-white px-3 text-sm normal-case text-[var(--ink)]" value={status} onChange={(event)=>setStatus(event.target.value as "all"|PurchaseRequestStatus)}><option value="all">Todos</option><option value="submitted">Pendientes</option><option value="approved">Aprobadas</option><option value="fulfilled">Cumplidas</option><option value="rejected">Rechazadas</option></select></label><label className="grid gap-1 text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Planta<select className="min-h-10 rounded-lg border border-[var(--line)] bg-white px-3 text-sm normal-case text-[var(--ink)]" value={plantId} onChange={(event)=>setPlantId(event.target.value)}><option value="all">Todas</option><option value="tamesis">Támesis</option><option value="yarumal">Yarumal</option></select></label></div></section>
    <section className="panel"><div className="section-head"><div><p className="eyebrow">Bandeja</p><h2>Solicitudes de compra</h2></div><span className="quiet">{filtered.length} mostradas</span></div>{filtered.length?<div className="grid gap-3">{filtered.map((request)=><RequestCard request={request} key={request.id}/>)}</div>:<div className="rounded-xl border border-dashed border-[var(--line)] p-8 text-center"><strong className="block text-sm">Sin solicitudes para estos filtros</strong><p className="quiet mt-2">Las solicitudes sirven para aprobar necesidades antes de registrar compras reales.</p></div>}</section></>;
}
