"use client";

import Link from "next/link";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { useSupplyStore } from "@/components/supply-store";
import { useMaintenanceStore } from "@/components/maintenance-store";
import { bogotaDateKey } from "@/lib/time";

export function SupplyConsumptionForm(){
  const router=useRouter();const {lots,consumeSupply}=useSupplyStore();const {equipment}=useMaintenanceStore();
  const [plantId,setPlantId]=useState("tamesis");const [lotKey,setLotKey]=useState("");const [quantity,setQuantity]=useState("");const [occurredOn,setOccurredOn]=useState(()=>bogotaDateKey(new Date()));const [destination,setDestination]=useState("");const [equipmentId,setEquipmentId]=useState("");const [processRef,setProcessRef]=useState("");const [note,setNote]=useState("");const [feedback,setFeedback]=useState("");const [busy,setBusy]=useState(false);
  const availableLots=useMemo(()=>lots.filter((l)=>l.plantId===plantId&&l.quantity>0),[lots,plantId]);const selected=availableLots.find((l)=>`${l.supplyId}|${l.lotCode}`===lotKey)??availableLots[0];const availableEquipment=equipment.filter((e)=>e.plantId===plantId);
  function save(){if(busy)return;if(!selected){setFeedback("No hay un lote con stock disponible en esta planta.");return;}setBusy(true);const result=consumeSupply({plantId,supplyId:selected.supplyId,lotCode:selected.lotCode,quantity:Number(quantity),occurredOn,destination,equipmentId:equipmentId||undefined,processRef,note});if(!result.ok){setFeedback(result.error);setBusy(false);return;}router.push("/supplies");}
  return <section className="panel mx-auto max-w-4xl"><div className="section-head"><div><p className="eyebrow">Kardex físico</p><h1 className="text-3xl">Registrar consumo de insumo</h1><p className="lede">Descuenta exactamente un lote físico y conserva el destino operacional.</p></div><Link className="button secondary" href="/supplies">Cancelar</Link></div><div className="grid gap-5 md:grid-cols-2">
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Planta<select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={plantId} onChange={(e)=>{setPlantId(e.target.value);setLotKey("");setEquipmentId("");}}><option value="tamesis">Támesis</option><option value="yarumal">Yarumal</option></select></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Fecha de consumo<input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" type="date" value={occurredOn} onChange={(e)=>setOccurredOn(e.target.value)}/></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)] md:col-span-2">Lote con stock<select aria-label="Lote con stock" className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={selected?`${selected.supplyId}|${selected.lotCode}`:""} onChange={(e)=>setLotKey(e.target.value)} disabled={!availableLots.length}><option value="">Seleccionar lote</option>{availableLots.map((l)=><option value={`${l.supplyId}|${l.lotCode}`} key={`${l.supplyId}-${l.lotCode}`}>{l.lotCode} · {l.supplyName} · {l.quantity.toLocaleString("es-CO")} {l.unit}</option>)}</select></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Cantidad consumida {selected?`(${selected.unit})`:""}<input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" inputMode="decimal" value={quantity} onChange={(e)=>setQuantity(e.target.value)} placeholder="Ej. 30"/></label>
    <div className="rounded-xl bg-[var(--surface-soft)] p-4"><span className="quiet">Disponible en lote</span><strong className="mt-1 block text-2xl">{selected?`${selected.quantity.toLocaleString("es-CO")} ${selected.unit}`:"—"}</strong><span className="mt-1 block text-xs text-[var(--muted)]">{selected?.supplyName??"Sin stock disponible"}</span></div>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)] md:col-span-2">Destino / uso<input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" value={destination} onChange={(e)=>setDestination(e.target.value)} placeholder="Ej. Formulación lote, mantenimiento molino"/></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Proceso relacionado <span className="font-normal">(opcional)</span><input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" value={processRef} onChange={(e)=>setProcessRef(e.target.value)} placeholder="Ej. Digestión, formulación"/></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Equipo relacionado <span className="font-normal">(opcional)</span><select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={equipmentId} onChange={(e)=>setEquipmentId(e.target.value)}><option value="">Sin equipo</option>{availableEquipment.map((e)=><option value={e.id} key={e.id}>{e.code} · {e.name}</option>)}</select></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)] md:col-span-2">Observación <span className="font-normal">(opcional)</span><textarea className="min-h-24 rounded-lg border border-[var(--line)] p-3 text-sm" value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Detalle del uso o novedad"/></label>
  </div><div className="mt-5 rounded-xl border border-dashed border-[var(--line)] p-4 text-xs text-[var(--muted)]"><strong className="text-[var(--ink)]">Al guardar:</strong> baja el stock físico del lote. No se crea gasto monetario ni costo contable automáticamente.</div>{feedback&&<p role="alert" className="mt-4 text-sm font-semibold text-[var(--red)]">{feedback}</p>}<div className="mt-6 flex justify-end"><button className="button primary" type="button" onClick={save} disabled={busy||!availableLots.length}>{busy?"Registrando consumo…":"Registrar consumo"}</button></div></section>;
}
