"use client";

import Link from "next/link";
import { useMemo,useState } from "react";
import { useExpenseStore } from "@/components/expense-store";
import { expenseCategories,expenseCategoryLabel,expenseRecordTypeLabel,totalRegisteredExpenseCop,type ExpenseCategory } from "@/lib/expense-domain";

const cop=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
function csvCell(value:string|number){const text=String(value);return /[;"\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}

export function ExpensesView(){
  const {expenses,suppliers}=useExpenseStore();const [plantId,setPlantId]=useState("all");const [category,setCategory]=useState<"all"|ExpenseCategory>("all");const [supplierId,setSupplierId]=useState("all");const filtered=useMemo(()=>expenses.filter((item)=>(plantId==="all"||item.plantId===plantId)&&(category==="all"||item.category===category)&&(supplierId==="all"||item.supplierId===supplierId)),[expenses,plantId,category,supplierId]);const total=totalRegisteredExpenseCop(filtered);const average=filtered.length?total/filtered.length:0;
  function exportCsv(){const rows:Array<Array<string|number>>=[["Fecha","Tipo","Planta","Proveedor","Categoría","Concepto","Monto COP","Documento","Solicitud origen","Equipo","Proceso","Evidencia","Nota"],...filtered.map((item)=>[item.documentDate,expenseRecordTypeLabel[item.recordType],item.plant,item.supplierName,expenseCategoryLabel[item.category],item.concept,item.amountCop,item.documentRef??"",item.purchaseRequestId??"",item.equipmentName??"",item.processRef??"",item.evidenceRef??"",item.note??""])];const blob=new Blob([rows.map((row)=>row.map(csvCell).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="greenatics-compras-gastos.csv";document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}
  return <><header className="page-header"><div><p className="eyebrow">Administración · ledger operacional</p><h1>Compras y gastos</h1><p className="lede">Registro trazable por planta, proveedor y categoría. El monto registrado es el hecho económico; sus pagos se registran por separado en Caja.</p></div><div className="header-actions"><Link className="button secondary" href="/purchases">Ver solicitudes</Link><button className="button secondary" type="button" onClick={exportCsv} disabled={!filtered.length}>Exportar CSV</button><Link className="button primary" href="/expenses/new">Registrar compra o gasto</Link></div></header>
    <section className="panel mb-4"><div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Planta<select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm normal-case text-[var(--ink)]" value={plantId} onChange={(event)=>setPlantId(event.target.value)}><option value="all">Todas</option><option value="tamesis">Támesis</option><option value="yarumal">Yarumal</option></select></label><label className="grid gap-1 text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Categoría<select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm normal-case text-[var(--ink)]" value={category} onChange={(event)=>setCategory(event.target.value as "all"|ExpenseCategory)}><option value="all">Todas</option>{expenseCategories.map((item)=><option value={item} key={item}>{expenseCategoryLabel[item]}</option>)}</select></label><label className="grid gap-1 text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Proveedor<select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm normal-case text-[var(--ink)]" value={supplierId} onChange={(event)=>setSupplierId(event.target.value)}><option value="all">Todos</option>{suppliers.slice().sort((a,b)=>a.name.localeCompare(b.name,"es")).map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div></section>
    <section className="metrics-grid" aria-label="Indicadores de compras y gastos"><div className="metric-block"><span>Monto registrado</span><strong>{cop.format(total)}</strong><small>No equivale a pagos realizados</small></div><div className="metric-block"><span>Registros</span><strong>{filtered.length}</strong><small>compras + gastos</small></div><div className="metric-block"><span>Promedio</span><strong>{filtered.length?cop.format(average):"—"}</strong><small>por registro filtrado</small></div><div className="metric-block"><span>Proveedores</span><strong>{new Set(filtered.map((item)=>item.supplierId)).size}</strong><small>en la selección</small></div></section>
    <section className="panel"><div className="section-head"><div><p className="eyebrow">Historial</p><h2>Registros append-only</h2></div><span className="quiet">{filtered.length} mostrados</span></div>{filtered.length?<div className="grid gap-2">{filtered.map((item)=><article className="rounded-xl border border-[var(--line)] p-4" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="status-pill status-planned">{expenseRecordTypeLabel[item.recordType]}</span>{item.purchaseRequestId&&<span className="status-pill status-normal">Desde solicitud</span>}<strong className="text-sm">{item.concept}</strong></div><span className="mt-1 block text-xs text-[var(--muted)]">{item.supplierName} · {item.plant} · {expenseCategoryLabel[item.category]}</span></div><div className="text-right"><strong className="block text-lg">{cop.format(item.amountCop)}</strong><span className="text-[11px] text-[var(--muted)]">{item.documentDate}</span></div></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 border-t border-[var(--line)] pt-3 text-[11px] text-[var(--muted)]">{item.documentRef&&<span>Documento: <strong className="text-[var(--ink)]">{item.documentRef}</strong></span>}{item.purchaseRequestId&&<span>Solicitud: <strong className="text-[var(--ink)]">{item.purchaseRequestId.slice(0,8)}…</strong></span>}{item.equipmentName&&<span>Equipo: <strong className="text-[var(--ink)]">{item.equipmentName}</strong></span>}{item.processRef&&<span>Proceso: <strong className="text-[var(--ink)]">{item.processRef}</strong></span>}<span>Liquidación: <strong className="text-[var(--ink)]">ver Caja</strong></span></div>{item.note&&<p className="mt-3 rounded-lg bg-[var(--surface-soft)] p-3 text-xs text-[var(--muted)]">{item.note}</p>}</article>)}</div>:<div className="rounded-xl border border-dashed border-[var(--line)] p-8 text-center"><strong className="block text-sm">Sin compras o gastos para estos filtros</strong><p className="quiet mt-2">Registrar un gasto no afecta inventario ni lo marca como pagado.</p></div>}</section></>;
}
