"use client";

import Link from "next/link";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { useExpenseStore } from "@/components/expense-store";
import { useSupplyStore } from "@/components/supply-store";
import { supplyCategoryLabel,type SupplyCategory } from "@/lib/supply-domain";
import type { InventoryUnit } from "@/lib/inventory-domain";
import { bogotaDateKey } from "@/lib/time";

export function SupplyReceiptForm(){
  const router=useRouter();const {expenses}=useExpenseStore();const {receiveSupply}=useSupplyStore();
  const [plantId,setPlantId]=useState("tamesis");const [name,setName]=useState("");const [category,setCategory]=useState<SupplyCategory>("input");const [unit,setUnit]=useState<InventoryUnit>("kg");const [quantity,setQuantity]=useState("");const [receivedOn,setReceivedOn]=useState(()=>bogotaDateKey(new Date()));const [expenseId,setExpenseId]=useState("");const [supplierName,setSupplierName]=useState("");const [documentRef,setDocumentRef]=useState("");const [evidenceRef,setEvidenceRef]=useState("");const [note,setNote]=useState("");const [feedback,setFeedback]=useState("");const [busy,setBusy]=useState(false);
  const purchaseExpenses=useMemo(()=>expenses.filter((e)=>e.plantId===plantId&&e.recordType==="purchase"),[expenses,plantId]);const linked=purchaseExpenses.find((e)=>e.id===expenseId);
  async function save(){if(busy)return;setBusy(true);setFeedback("");const result=await receiveSupply({plantId,supplyName:name,category,unit,quantity:Number(quantity),receivedOn,supplierName:linked?.supplierName??supplierName,expenseId:expenseId||undefined,documentRef:documentRef||linked?.documentRef,evidenceRef,note});if(!result.ok){setFeedback(result.error);setBusy(false);return;}router.push("/supplies");}
  return <section className="panel mx-auto max-w-4xl"><div className="section-head"><div><p className="eyebrow">Ingreso de materia prima / insumo</p><h1 className="text-3xl">Registrar recepción física</h1><p className="lede">Mide lo que realmente llegó a planta. Una compra o un pago previo no define esta cantidad.</p></div><Link className="button secondary" href="/supplies">Cancelar</Link></div><div className="grid min-w-0 gap-5 md:grid-cols-2">
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Planta<select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={plantId} onChange={(e)=>{setPlantId(e.target.value);setExpenseId("");}} disabled={busy}><option value="tamesis">Támesis</option><option value="yarumal">Yarumal</option></select></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Fecha de recepción<input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" type="date" value={receivedOn} onChange={(e)=>setReceivedOn(e.target.value)} disabled={busy}/></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)] md:col-span-2">Insumo recibido<input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" value={name} onChange={(e)=>setName(e.target.value)} placeholder="Ej. Melaza, ácido húmico, envase 1 L" disabled={busy}/></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Categoría<select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={category} onChange={(e)=>setCategory(e.target.value as SupplyCategory)} disabled={busy}>{Object.entries(supplyCategoryLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Unidad<select className="min-h-11 rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={unit} onChange={(e)=>setUnit(e.target.value as InventoryUnit)} disabled={busy}><option value="kg">kg</option><option value="L">L</option><option value="unidades">unidades</option></select></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Cantidad medida<input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" inputMode="decimal" value={quantity} onChange={(e)=>setQuantity(e.target.value)} placeholder="Ej. 100" disabled={busy}/></label>
    <label className="grid min-w-0 gap-2 text-xs font-bold text-[var(--muted)]">Compra real relacionada <span className="font-normal">(opcional)</span><select className="min-h-11 w-full min-w-0 max-w-full rounded-lg border border-[var(--line)] bg-white px-3 text-sm" value={expenseId} onChange={(e)=>setExpenseId(e.target.value)} disabled={busy}><option value="">Sin enlace financiero</option>{purchaseExpenses.map((e)=><option key={e.id} value={e.id}>{e.documentDate} · {e.supplierName} · {e.concept}</option>)}</select></label>
    {!linked&&<label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Proveedor / origen <span className="font-normal">(opcional)</span><input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" value={supplierName} onChange={(e)=>setSupplierName(e.target.value)} placeholder="Si no hay compra enlazada" disabled={busy}/></label>}
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Documento <span className="font-normal">(opcional)</span><input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" value={documentRef} onChange={(e)=>setDocumentRef(e.target.value)} placeholder={linked?.documentRef??"Remisión / soporte"} disabled={busy}/></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)]">Evidencia <span className="font-normal">(opcional)</span><input className="min-h-11 rounded-lg border border-[var(--line)] px-3 text-sm" value={evidenceRef} onChange={(e)=>setEvidenceRef(e.target.value)} placeholder="Foto, URL o referencia" disabled={busy}/></label>
    <label className="grid gap-2 text-xs font-bold text-[var(--muted)] md:col-span-2">Observación <span className="font-normal">(opcional)</span><textarea className="min-h-24 rounded-lg border border-[var(--line)] p-3 text-sm" value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Estado, diferencia frente a documento, novedad de recepción" disabled={busy}/></label>
  </div>{linked&&<div className="mt-5 rounded-xl bg-[var(--surface-soft)] p-4 text-xs"><strong>Compra enlazada:</strong> {linked.supplierName} · {linked.concept}. <span className="text-[var(--muted)]">Su monto COP no determina la cantidad física recibida.</span></div>}<div className="mt-5 rounded-xl border border-dashed border-[var(--line)] p-4 text-xs text-[var(--muted)]"><strong className="text-[var(--ink)]">Al guardar:</strong> se crea un lote físico y una entrada al kardex. No se crea compra, pago ni consumo.</div>{feedback&&<p role="alert" className="mt-4 text-sm font-semibold text-[var(--red)]">{feedback}</p>}<div className="mt-6 flex justify-end"><button className="button primary" type="button" onClick={()=>void save()} disabled={busy}>{busy?"Registrando recepción…":"Registrar recepción física"}</button></div></section>;
}
